<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_FAQs</name>
   <tag></tag>
   <elementGuidId>c9a72573-9f6a-451c-8a85-7c3bd65a8278</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='body-root']/maids-visa-root/maids-visa-layout/div/maids-visa-header/div/div/div/div[2]/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.airbnb-medium.nav-link.gtm-header-faq</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7684d400-4276-40a7-95b2-2914e6c1680e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>faq</value>
      <webElementGuid>57c2ff59-fb1f-4a39-87af-d919262c3973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>airbnb-medium nav-link gtm-header-faq</value>
      <webElementGuid>f56d7057-120d-4651-b87e-6307f369fab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> FAQs </value>
      <webElementGuid>940fc044-9945-472f-8b72-9c672d2c07c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body-root&quot;)/maids-visa-root[1]/maids-visa-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content&quot;]/maids-visa-header[1]/div[@class=&quot;header&quot;]/div[@class=&quot;container-xl&quot;]/div[@class=&quot;d-flex align-items-center align-items-md-end&quot;]/div[@class=&quot;navbarNavDropdown&quot;]/ul[@class=&quot;navbar-nav width_100 flex-row align-items-center ng-star-inserted&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;airbnb-medium nav-link gtm-header-faq&quot;]</value>
      <webElementGuid>e4974886-b037-4b47-a01c-a6754c8d8623</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body-root']/maids-visa-root/maids-visa-layout/div/maids-visa-header/div/div/div/div[2]/ul/li[2]/a</value>
      <webElementGuid>b6e7d4d6-c868-4a95-a4f8-8e83c054632b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'FAQs')]</value>
      <webElementGuid>f41e9002-d873-4d42-80e4-c41d98d7e367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[1]/following::a[1]</value>
      <webElementGuid>859d6ef2-7610-42cc-9d93-f8f16f52172a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hire A Maid'])[1]/preceding::a[1]</value>
      <webElementGuid>c472129b-990e-45b5-90d0-cac003099c78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WhatsApp'])[1]/preceding::a[2]</value>
      <webElementGuid>0ca6b1f7-e20d-49f6-8d00-8636c94c35c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FAQs']/parent::*</value>
      <webElementGuid>69df1f9a-4d44-4c99-b500-80df094c6e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'faq')]</value>
      <webElementGuid>ffda2071-1e57-4e2f-8882-3bb3f7582e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>a49ffe64-a454-49e8-905c-7eafba797585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'faq' and (text() = ' FAQs ' or . = ' FAQs ')]</value>
      <webElementGuid>ffeb8da8-b49d-4ac0-9035-2c4e8fcaa2c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
